@startuml
actor utilisateur
participant "cont : ControleurVueTemporaireClasse" as cont
participant "vue : VueDependances" as vue

utilisateur -> cont : Clique sur le bouton "ajouter dependance"
activate cont

    cont -> vue : notifier(Sujet s)
    activate vue
    vue -> vue : vueChoisirClasse
    vue -> vue : vueChoisirFleche
    cont <-- vue
    deactivate vue

utilisateur <-- cont : visuel mise a jour
deactivate cont
@enduml