@startuml
actor utilisateur
participant "vueExt : VueSousMenuClassExt" as vueExt
participant "analyseur : Analyseur" as analyse
participant "classe : Classe" as classe
participant "vueClasse : VueClasse" as vueClasse
participant "model: Model" as model
utilisateur -> vueExt : clique sur une classe
activate vueExt
vueExt -> analyse : analyse()
activate analyse
vueExt <-- analyse : classe
deactivate analyse
vueExt -> classe : ajouterObservateur(vueClasse)
vueExt -> model : addClasse(classe)
utilisateur <-- vueExt : visuel mis à jour

@enduml